server:
  port: 8080

eureka:
  instance:
    port: ${EUREKA_PORT:8761}
    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 5
#    leaseExpirationDurationInSeconds: 10
    instance-id: ${spring.application.name}:${random.value}
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/current_savings
    #    username: postgres
    #    password: root
    url: jdbc:postgresql://10.42.65.131:4550/sbicloud_bd
    username: bits
    password: biTS@#123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: postgres
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  config: classpath:log/logback-alpha.xml
  hibernate:
    ddl-auto: none

